### ISSUE TITLE
Which is the latest build of SuperiorOS for FAJITA?

### ISSUE THREAD

**Issue by sfksuperman** [SuperiorOS-Devices/changelogs#185]
Inside **gapps** folder, there are 4 files. Their build numbers and modified date are confusing me.
<img width="598" alt="image" src="https://github.com/SuperiorOS-Devices/changelogs/assets/34414624/cc76a25c-f772-4382-92df-c9ba23986fb0">

In the parent folder, there is one more build:
<img width="573" alt="image" src="https://github.com/SuperiorOS-Devices/changelogs/assets/34414624/7168d0a5-c4ec-4330-a8f7-606f574037e8">

**Please clarify which one is the latest Gapps build to flash. Thanks.**

**Comment by Darkstar085** [comment]
Use the 20/11 build
